---
google:
  secrets:
    client_id: download from google projecs console, section <installed>
    project_id: ....
    auth_uri: ....
    token_uri: ....
    auth_provider_x509_cert_url: ....
    client_secret: ....
    redirect_uris:
    - ....
    - ....
  token:
    access_token: ....
    expires_in: 3600
    refresh_token: ....
    token_type: Bearer
  group:
    work: ...
    friends: ...
  backup: ...
exchange:
  username: ...
  password: ...
  email: ...
  domain: ...
  cachedir: ...
locale: NL
